Updated to cos-81-lts due to cos-77-lts deprecation
GoogleCloudPlatform/gke-migration-to-containers pull request #49
Opened 2021-09-08 09:14 UTC by ferranespigares

cos-77-lts has been deprecated since April 2021 according to [https://cloud.google.com/container-optimized-os/docs/release-notes#Archived](url). In order for the "make deploy" to succeed, it has to be updated to cos-81-lts.
This solved the deployment problem on a Qwiklabs lab (Migrating to GKE Containers).

Regards
Ferran

2021-09-08 09:17 UTC, ferranespigares commented
@googlebot I signed it!

2021-09-09 01:24 UTC, cnkang commented
I would suggest update to " cos-89-lts", since cos-81-lts will be end of support by Sep 2021, as documented here: https://cloud.google.com/container-optimized-os/docs/release-notes#Current

2021-09-14 17:43 UTC, rosera commented
> I would suggest update to " cos-89-lts", since cos-81-lts will be end of support by Sep 2021, as documented here: https://cloud.google.com/container-optimized-os/docs/release-notes#Current

Is there a reason - this cant be updated to cos-stable?

2021-09-15 18:56 UTC, rosera requested changes
Can this be changed to cos-stable instead - it would make it more portable.

2021-09-20 16:35 UTC, kaariger approved these changes

2021-09-20 16:35 UTC, merged